### ISSUE TITLE
ModuleNotFoundError: No module named 'lpips_pytorch'

### ISSUE THREAD

**Issue by lchia** [WangLiwen1994/DeepRelight#2]
python test.py

**Comment by lchia** [comment]
Traceback (most recent call last):
  File "test.py", line 41, in <module>
    model = create_model(opt)
  File "/home/happy/projects/AIM2020/DeepRelight-master/models/models.py", line 5, in create_model
    from .pix2pixHD_model import Pix2PixHDModel, InferenceModel
  File "/home/happy/projects/AIM2020/DeepRelight-master/models/pix2pixHD_model.py", line 9, in <module>
    from lpips_pytorch import LPIPS, lpips
ModuleNotFoundError: No module named 'lpips_pytorch'

**Comment by WangLiwen1994** [comment]
Hi, please try to install the package through

`pip install git+https://github.com/S-aiueo32/lpips-pytorch.git`

**Comment by lchia** [comment]
OK, it works. Thanks.
